#!/bin/bash

echo Octronic Dream Tool

echo Looking for ./node_modules
if [ ! -d node_modules ]; then
    echo Installing Node Modules...
    npm install
    echo Done
fi

echo Starting Dream Tool

npm start
